// Generated by gencpp from file example_ros_msg/VecOfDoubles.msg
// DO NOT EDIT!


#ifndef EXAMPLE_ROS_MSG_MESSAGE_VECOFDOUBLES_H
#define EXAMPLE_ROS_MSG_MESSAGE_VECOFDOUBLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace example_ros_msg
{
template <class ContainerAllocator>
struct VecOfDoubles_
{
  typedef VecOfDoubles_<ContainerAllocator> Type;

  VecOfDoubles_()
    : db1_vec()  {
    }
  VecOfDoubles_(const ContainerAllocator& _alloc)
    : db1_vec(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _db1_vec_type;
  _db1_vec_type db1_vec;





  typedef boost::shared_ptr< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> const> ConstPtr;

}; // struct VecOfDoubles_

typedef ::example_ros_msg::VecOfDoubles_<std::allocator<void> > VecOfDoubles;

typedef boost::shared_ptr< ::example_ros_msg::VecOfDoubles > VecOfDoublesPtr;
typedef boost::shared_ptr< ::example_ros_msg::VecOfDoubles const> VecOfDoublesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::example_ros_msg::VecOfDoubles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::example_ros_msg::VecOfDoubles_<ContainerAllocator1> & lhs, const ::example_ros_msg::VecOfDoubles_<ContainerAllocator2> & rhs)
{
  return lhs.db1_vec == rhs.db1_vec;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::example_ros_msg::VecOfDoubles_<ContainerAllocator1> & lhs, const ::example_ros_msg::VecOfDoubles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace example_ros_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "103cc761631b433aad855c490af308f7";
  }

  static const char* value(const ::example_ros_msg::VecOfDoubles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x103cc761631b433aULL;
  static const uint64_t static_value2 = 0xad855c490af308f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "example_ros_msg/VecOfDoubles";
  }

  static const char* value(const ::example_ros_msg::VecOfDoubles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] db1_vec\n"
;
  }

  static const char* value(const ::example_ros_msg::VecOfDoubles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.db1_vec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VecOfDoubles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::example_ros_msg::VecOfDoubles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::example_ros_msg::VecOfDoubles_<ContainerAllocator>& v)
  {
    s << indent << "db1_vec[]" << std::endl;
    for (size_t i = 0; i < v.db1_vec.size(); ++i)
    {
      s << indent << "  db1_vec[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.db1_vec[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAMPLE_ROS_MSG_MESSAGE_VECOFDOUBLES_H
