(cl:defpackage example_ros_msg-srv
  (:use )
  (:export
   "EXAMPLESERVICEMSG"
   "<EXAMPLESERVICEMSG-REQUEST>"
   "EXAMPLESERVICEMSG-REQUEST"
   "<EXAMPLESERVICEMSG-RESPONSE>"
   "EXAMPLESERVICEMSG-RESPONSE"
  ))

